### ISSUE TITLE
Not generating thumbnails for videos

### ISSUE THREAD

**Issue by allanaaa** [omeka/plugin-DerivativeImages#9]
On a 3.0.3 install, and then on 3.1 after upgrading, this plugin isn't generating any thumbnails for videos in my installation. 

I have movies imported from the National Mall collection:
http://dev.omeka.org/amayer/amayer-c/omeka/items/browse?search=&advanced%5B0%5D%5Bjoiner%5D=and&advanced%5B0%5D%5Belement_id%5D=&advanced%5B0%5D%5Btype%5D=&advanced%5B0%5D%5Bterms%5D=&range=&collection=99&type=3&user=&tags=&public=&featured=&geolocation-mapped=&geolocation-address=&geolocation-latitude=&geolocation-longitude=&geolocation-radius=10&exhibit=&submit_search=Search+for+items

They seem to be all mp4s. I don't think I have any other video formats. 

In the plugin, I tried first to generate for any files that didn't have derivative images; no luck. Then I tried by file types, no luck. Then I tried to generate for all files, no luck (although it's hard to tell if the process is finished or just taking a really long time).

**Comment by zerocrates** [comment]
The plugin only just reruns the normal thumbnail creation process. So whether or not video is supported is down to the specific server, not anything in this plugin's control.
